# Sets the version: field to `v1beta1`.
# It's not obvious how to do this with kubebuilder annotations.

resources:
- crds/templates.gatekeeper.sh_constrainttemplates.yaml

patches:
- target:
    group: apiextensions.k8s.io
    version: v1beta1
    kind: CustomResourceDefinition
    name: constrainttemplates.templates.gatekeeper.sh
  patch: |-
    - op: remove
      path: /spec/version
